import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Tab } from "@headlessui/react";

const tabs = [
  {
    key: "All",
    display: "All",
  },
  {
    key: "Music photos",
    display: "Music photos",
  },
  {
    key: "Other stuff",
    display: "Other stuff",
  },
];
export default function Home() {
  return (
    <div className="flex flex-col h-full bg-[url('/trevortwomeyselfie.jpeg')] bg-top bg-cover">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by Create next app" />
        <link rel="stylesheet" href="/favicon.ico" />
      </Head>
      <header className="flex justify-between items-center h-[90px] px-6">
        <div>
          <img
            src="/waterlogo.PNG"
            alt="Logo"
            width="150"
            height="50"
            px-3
            py-2
          />
        </div>
        <Link
          href="#"
          className="rounded-3xl bg-white text-stone-700 px-3 py-2 hover:bg-opacity-90">
          Get in touch
        </Link>
      </header>
      <main className="grow">
        <div className="flex flex-col items-center h-full">
          <Tab.Group>
            <Tab.List className="flex items-center gap-12">
              {tabs.map((tab) => (
                <Tab key={tab.key} className="p-2">
                  {({ selected }) => (
                    <span
                      className={selected ? "text-white" : "text-stone-600"}>
                      {tab.display}
                    </span>
                  )}
                </Tab>
              ))}
            </Tab.List>
            <Tab.Panels className="h-full bg-stone-900 bg-opacity-80 h-full max-w-[900px] w-full p-2 sm:p-4 my-6">
              <Tab.Panel className="">
                All Photos
              </Tab.Panel>
              <Tab.Panel>Music Photos</Tab.Panel>
              <Tab.Panel>Other stuff</Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </main>

      <footer className="h-[60px] flex justify-center items-center">
        <p>Trevor Twomey Photography</p>
      </footer>
    </div>
  );
}
